name: Update data
on: [push]


jobs:
  render:
    name: Update data
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install tidyverse and rvest
        run: Rscript -e 'install.packages(c("tidyverse", "rvest"))'
      - name: Repull data
        run: Rscript covid_downloaders.R
      - name: Commit results
        run: |
          git status
          git commit data/covid.RData -m 'Update data' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
