on:
  push:
    paths:
      - covid_downloader.R

name: Test data

jobs:
  render:
    name: Test data
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install rmarkdown
        run: Rscript -e 'install.packages(c("tidyverse", "rvest"))'
      - name: Render README
        run: Rscript -e 'source("covid_downloader.R")'
      - name: Commit results
        run: |
          git commit data/covid.Rdata -m 'Update data' || echo "No changes to commit"
          git push origin || echo "No changes to commit"


